version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - '5672:5672'
      - '15672:15672'

  app:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - '${PORT}:3000'
    depends_on:
      - mongo
      - redis
      - rabbitmq

volumes:
  mongo_data:
